### ISSUE TITLE
push全屏的webViewController时，tabbar的位置会有黑块一闪而过

### ISSUE THREAD

**Issue by empheng** [wanyakun/YKNavigationController#1]
rt. 同jt版本的issue 7

**Comment by empheng** [comment]
设置webViewController的底色，同时设置opaque属性NO

**Comment by wanyakun** [comment]
webViewController设置edgesForExtendedLayout = UIRectEdgeAll或者bottom，这样controller向下延伸，就不会导致上一页tabbar占有区域变黑色了。
